/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RockyMountainLakeToursRouteImport } from './routes/rocky-mountain-lake-tours'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZhIndexRouteImport } from './routes/zh/index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as KoIndexRouteImport } from './routes/ko/index'
import { Route as ZhTermsRouteImport } from './routes/zh/terms'
import { Route as ZhRockyMountainLakeToursRouteImport } from './routes/zh/rocky-mountain-lake-tours'
import { Route as ZhReviewsRouteImport } from './routes/zh/reviews'
import { Route as ZhPrivacyRouteImport } from './routes/zh/privacy'
import { Route as ZhGalleryRouteImport } from './routes/zh/gallery'
import { Route as ZhFaqRouteImport } from './routes/zh/faq'
import { Route as ZhDestinationsRouteImport } from './routes/zh/destinations'
import { Route as ZhContactRouteImport } from './routes/zh/contact'
import { Route as ZhBlogRouteImport } from './routes/zh/blog'
import { Route as ZhAboutRouteImport } from './routes/zh/about'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as KoTermsRouteImport } from './routes/ko/terms'
import { Route as KoRockyMountainLakeToursRouteImport } from './routes/ko/rocky-mountain-lake-tours'
import { Route as KoReviewsRouteImport } from './routes/ko/reviews'
import { Route as KoPrivacyRouteImport } from './routes/ko/privacy'
import { Route as KoFaqRouteImport } from './routes/ko/faq'
import { Route as KoDestinationsRouteImport } from './routes/ko/destinations'
import { Route as KoContactRouteImport } from './routes/ko/contact'
import { Route as KoBlogRouteImport } from './routes/ko/blog'
import { Route as KoAboutRouteImport } from './routes/ko/about'
import { Route as ZhToursIndexRouteImport } from './routes/zh/tours.index'
import { Route as KoToursIndexRouteImport } from './routes/ko/tours.index'
import { Route as ZhToursSlugRouteImport } from './routes/zh/tours.$slug'
import { Route as KoToursSlugRouteImport } from './routes/ko/tours.$slug'

const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RockyMountainLakeToursRoute = RockyMountainLakeToursRouteImport.update({
  id: '/rocky-mountain-lake-tours',
  path: '/rocky-mountain-lake-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/zh/',
  path: '/zh/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToursRoute,
} as any)
const KoIndexRoute = KoIndexRouteImport.update({
  id: '/ko/',
  path: '/ko/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhTermsRoute = ZhTermsRouteImport.update({
  id: '/zh/terms',
  path: '/zh/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhRockyMountainLakeToursRoute =
  ZhRockyMountainLakeToursRouteImport.update({
    id: '/zh/rocky-mountain-lake-tours',
    path: '/zh/rocky-mountain-lake-tours',
    getParentRoute: () => rootRouteImport,
  } as any)
const ZhReviewsRoute = ZhReviewsRouteImport.update({
  id: '/zh/reviews',
  path: '/zh/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhPrivacyRoute = ZhPrivacyRouteImport.update({
  id: '/zh/privacy',
  path: '/zh/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhGalleryRoute = ZhGalleryRouteImport.update({
  id: '/zh/gallery',
  path: '/zh/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhFaqRoute = ZhFaqRouteImport.update({
  id: '/zh/faq',
  path: '/zh/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhDestinationsRoute = ZhDestinationsRouteImport.update({
  id: '/zh/destinations',
  path: '/zh/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhContactRoute = ZhContactRouteImport.update({
  id: '/zh/contact',
  path: '/zh/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhBlogRoute = ZhBlogRouteImport.update({
  id: '/zh/blog',
  path: '/zh/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhAboutRoute = ZhAboutRouteImport.update({
  id: '/zh/about',
  path: '/zh/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToursRoute,
} as any)
const KoTermsRoute = KoTermsRouteImport.update({
  id: '/ko/terms',
  path: '/ko/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const KoRockyMountainLakeToursRoute =
  KoRockyMountainLakeToursRouteImport.update({
    id: '/ko/rocky-mountain-lake-tours',
    path: '/ko/rocky-mountain-lake-tours',
    getParentRoute: () => rootRouteImport,
  } as any)
const KoReviewsRoute = KoReviewsRouteImport.update({
  id: '/ko/reviews',
  path: '/ko/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const KoPrivacyRoute = KoPrivacyRouteImport.update({
  id: '/ko/privacy',
  path: '/ko/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const KoFaqRoute = KoFaqRouteImport.update({
  id: '/ko/faq',
  path: '/ko/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const KoDestinationsRoute = KoDestinationsRouteImport.update({
  id: '/ko/destinations',
  path: '/ko/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const KoContactRoute = KoContactRouteImport.update({
  id: '/ko/contact',
  path: '/ko/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const KoBlogRoute = KoBlogRouteImport.update({
  id: '/ko/blog',
  path: '/ko/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const KoAboutRoute = KoAboutRouteImport.update({
  id: '/ko/about',
  path: '/ko/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhToursIndexRoute = ZhToursIndexRouteImport.update({
  id: '/zh/tours/',
  path: '/zh/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoToursIndexRoute = KoToursIndexRouteImport.update({
  id: '/ko/tours/',
  path: '/ko/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhToursSlugRoute = ZhToursSlugRouteImport.update({
  id: '/zh/tours/$slug',
  path: '/zh/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KoToursSlugRoute = KoToursSlugRouteImport.update({
  id: '/ko/tours/$slug',
  path: '/ko/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/rocky-mountain-lake-tours': typeof RockyMountainLakeToursRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tours': typeof ToursRouteWithChildren
  '/ko/about': typeof KoAboutRoute
  '/ko/blog': typeof KoBlogRoute
  '/ko/contact': typeof KoContactRoute
  '/ko/destinations': typeof KoDestinationsRoute
  '/ko/faq': typeof KoFaqRoute
  '/ko/privacy': typeof KoPrivacyRoute
  '/ko/reviews': typeof KoReviewsRoute
  '/ko/rocky-mountain-lake-tours': typeof KoRockyMountainLakeToursRoute
  '/ko/terms': typeof KoTermsRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/blog': typeof ZhBlogRoute
  '/zh/contact': typeof ZhContactRoute
  '/zh/destinations': typeof ZhDestinationsRoute
  '/zh/faq': typeof ZhFaqRoute
  '/zh/gallery': typeof ZhGalleryRoute
  '/zh/privacy': typeof ZhPrivacyRoute
  '/zh/reviews': typeof ZhReviewsRoute
  '/zh/rocky-mountain-lake-tours': typeof ZhRockyMountainLakeToursRoute
  '/zh/terms': typeof ZhTermsRoute
  '/ko/': typeof KoIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/ko/tours/$slug': typeof KoToursSlugRoute
  '/zh/tours/$slug': typeof ZhToursSlugRoute
  '/ko/tours/': typeof KoToursIndexRoute
  '/zh/tours/': typeof ZhToursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/rocky-mountain-lake-tours': typeof RockyMountainLakeToursRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/blog': typeof KoBlogRoute
  '/ko/contact': typeof KoContactRoute
  '/ko/destinations': typeof KoDestinationsRoute
  '/ko/faq': typeof KoFaqRoute
  '/ko/privacy': typeof KoPrivacyRoute
  '/ko/reviews': typeof KoReviewsRoute
  '/ko/rocky-mountain-lake-tours': typeof KoRockyMountainLakeToursRoute
  '/ko/terms': typeof KoTermsRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/blog': typeof ZhBlogRoute
  '/zh/contact': typeof ZhContactRoute
  '/zh/destinations': typeof ZhDestinationsRoute
  '/zh/faq': typeof ZhFaqRoute
  '/zh/gallery': typeof ZhGalleryRoute
  '/zh/privacy': typeof ZhPrivacyRoute
  '/zh/reviews': typeof ZhReviewsRoute
  '/zh/rocky-mountain-lake-tours': typeof ZhRockyMountainLakeToursRoute
  '/zh/terms': typeof ZhTermsRoute
  '/ko': typeof KoIndexRoute
  '/tours': typeof ToursIndexRoute
  '/zh': typeof ZhIndexRoute
  '/ko/tours/$slug': typeof KoToursSlugRoute
  '/zh/tours/$slug': typeof ZhToursSlugRoute
  '/ko/tours': typeof KoToursIndexRoute
  '/zh/tours': typeof ZhToursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/rocky-mountain-lake-tours': typeof RockyMountainLakeToursRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tours': typeof ToursRouteWithChildren
  '/ko/about': typeof KoAboutRoute
  '/ko/blog': typeof KoBlogRoute
  '/ko/contact': typeof KoContactRoute
  '/ko/destinations': typeof KoDestinationsRoute
  '/ko/faq': typeof KoFaqRoute
  '/ko/privacy': typeof KoPrivacyRoute
  '/ko/reviews': typeof KoReviewsRoute
  '/ko/rocky-mountain-lake-tours': typeof KoRockyMountainLakeToursRoute
  '/ko/terms': typeof KoTermsRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/blog': typeof ZhBlogRoute
  '/zh/contact': typeof ZhContactRoute
  '/zh/destinations': typeof ZhDestinationsRoute
  '/zh/faq': typeof ZhFaqRoute
  '/zh/gallery': typeof ZhGalleryRoute
  '/zh/privacy': typeof ZhPrivacyRoute
  '/zh/reviews': typeof ZhReviewsRoute
  '/zh/rocky-mountain-lake-tours': typeof ZhRockyMountainLakeToursRoute
  '/zh/terms': typeof ZhTermsRoute
  '/ko/': typeof KoIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/ko/tours/$slug': typeof KoToursSlugRoute
  '/zh/tours/$slug': typeof ZhToursSlugRoute
  '/ko/tours/': typeof KoToursIndexRoute
  '/zh/tours/': typeof ZhToursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/reviews'
    | '/rocky-mountain-lake-tours'
    | '/sitemap.xml'
    | '/terms'
    | '/tours'
    | '/ko/about'
    | '/ko/blog'
    | '/ko/contact'
    | '/ko/destinations'
    | '/ko/faq'
    | '/ko/privacy'
    | '/ko/reviews'
    | '/ko/rocky-mountain-lake-tours'
    | '/ko/terms'
    | '/tours/$slug'
    | '/zh/about'
    | '/zh/blog'
    | '/zh/contact'
    | '/zh/destinations'
    | '/zh/faq'
    | '/zh/gallery'
    | '/zh/privacy'
    | '/zh/reviews'
    | '/zh/rocky-mountain-lake-tours'
    | '/zh/terms'
    | '/ko/'
    | '/tours/'
    | '/zh/'
    | '/ko/tours/$slug'
    | '/zh/tours/$slug'
    | '/ko/tours/'
    | '/zh/tours/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/reviews'
    | '/rocky-mountain-lake-tours'
    | '/sitemap.xml'
    | '/terms'
    | '/ko/about'
    | '/ko/blog'
    | '/ko/contact'
    | '/ko/destinations'
    | '/ko/faq'
    | '/ko/privacy'
    | '/ko/reviews'
    | '/ko/rocky-mountain-lake-tours'
    | '/ko/terms'
    | '/tours/$slug'
    | '/zh/about'
    | '/zh/blog'
    | '/zh/contact'
    | '/zh/destinations'
    | '/zh/faq'
    | '/zh/gallery'
    | '/zh/privacy'
    | '/zh/reviews'
    | '/zh/rocky-mountain-lake-tours'
    | '/zh/terms'
    | '/ko'
    | '/tours'
    | '/zh'
    | '/ko/tours/$slug'
    | '/zh/tours/$slug'
    | '/ko/tours'
    | '/zh/tours'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/reviews'
    | '/rocky-mountain-lake-tours'
    | '/sitemap.xml'
    | '/terms'
    | '/tours'
    | '/ko/about'
    | '/ko/blog'
    | '/ko/contact'
    | '/ko/destinations'
    | '/ko/faq'
    | '/ko/privacy'
    | '/ko/reviews'
    | '/ko/rocky-mountain-lake-tours'
    | '/ko/terms'
    | '/tours/$slug'
    | '/zh/about'
    | '/zh/blog'
    | '/zh/contact'
    | '/zh/destinations'
    | '/zh/faq'
    | '/zh/gallery'
    | '/zh/privacy'
    | '/zh/reviews'
    | '/zh/rocky-mountain-lake-tours'
    | '/zh/terms'
    | '/ko/'
    | '/tours/'
    | '/zh/'
    | '/ko/tours/$slug'
    | '/zh/tours/$slug'
    | '/ko/tours/'
    | '/zh/tours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  RockyMountainLakeToursRoute: typeof RockyMountainLakeToursRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToursRoute: typeof ToursRouteWithChildren
  KoAboutRoute: typeof KoAboutRoute
  KoBlogRoute: typeof KoBlogRoute
  KoContactRoute: typeof KoContactRoute
  KoDestinationsRoute: typeof KoDestinationsRoute
  KoFaqRoute: typeof KoFaqRoute
  KoPrivacyRoute: typeof KoPrivacyRoute
  KoReviewsRoute: typeof KoReviewsRoute
  KoRockyMountainLakeToursRoute: typeof KoRockyMountainLakeToursRoute
  KoTermsRoute: typeof KoTermsRoute
  ZhAboutRoute: typeof ZhAboutRoute
  ZhBlogRoute: typeof ZhBlogRoute
  ZhContactRoute: typeof ZhContactRoute
  ZhDestinationsRoute: typeof ZhDestinationsRoute
  ZhFaqRoute: typeof ZhFaqRoute
  ZhGalleryRoute: typeof ZhGalleryRoute
  ZhPrivacyRoute: typeof ZhPrivacyRoute
  ZhReviewsRoute: typeof ZhReviewsRoute
  ZhRockyMountainLakeToursRoute: typeof ZhRockyMountainLakeToursRoute
  ZhTermsRoute: typeof ZhTermsRoute
  KoIndexRoute: typeof KoIndexRoute
  ZhIndexRoute: typeof ZhIndexRoute
  KoToursSlugRoute: typeof KoToursSlugRoute
  ZhToursSlugRoute: typeof ZhToursSlugRoute
  KoToursIndexRoute: typeof KoToursIndexRoute
  ZhToursIndexRoute: typeof ZhToursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rocky-mountain-lake-tours': {
      id: '/rocky-mountain-lake-tours'
      path: '/rocky-mountain-lake-tours'
      fullPath: '/rocky-mountain-lake-tours'
      preLoaderRoute: typeof RockyMountainLakeToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/': {
      id: '/zh/'
      path: '/zh'
      fullPath: '/zh/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof ToursRoute
    }
    '/ko/': {
      id: '/ko/'
      path: '/ko'
      fullPath: '/ko/'
      preLoaderRoute: typeof KoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/terms': {
      id: '/zh/terms'
      path: '/zh/terms'
      fullPath: '/zh/terms'
      preLoaderRoute: typeof ZhTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/rocky-mountain-lake-tours': {
      id: '/zh/rocky-mountain-lake-tours'
      path: '/zh/rocky-mountain-lake-tours'
      fullPath: '/zh/rocky-mountain-lake-tours'
      preLoaderRoute: typeof ZhRockyMountainLakeToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reviews': {
      id: '/zh/reviews'
      path: '/zh/reviews'
      fullPath: '/zh/reviews'
      preLoaderRoute: typeof ZhReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/privacy': {
      id: '/zh/privacy'
      path: '/zh/privacy'
      fullPath: '/zh/privacy'
      preLoaderRoute: typeof ZhPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/gallery': {
      id: '/zh/gallery'
      path: '/zh/gallery'
      fullPath: '/zh/gallery'
      preLoaderRoute: typeof ZhGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/faq': {
      id: '/zh/faq'
      path: '/zh/faq'
      fullPath: '/zh/faq'
      preLoaderRoute: typeof ZhFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/destinations': {
      id: '/zh/destinations'
      path: '/zh/destinations'
      fullPath: '/zh/destinations'
      preLoaderRoute: typeof ZhDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/contact': {
      id: '/zh/contact'
      path: '/zh/contact'
      fullPath: '/zh/contact'
      preLoaderRoute: typeof ZhContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/blog': {
      id: '/zh/blog'
      path: '/zh/blog'
      fullPath: '/zh/blog'
      preLoaderRoute: typeof ZhBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/about': {
      id: '/zh/about'
      path: '/zh/about'
      fullPath: '/zh/about'
      preLoaderRoute: typeof ZhAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof ToursRoute
    }
    '/ko/terms': {
      id: '/ko/terms'
      path: '/ko/terms'
      fullPath: '/ko/terms'
      preLoaderRoute: typeof KoTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/rocky-mountain-lake-tours': {
      id: '/ko/rocky-mountain-lake-tours'
      path: '/ko/rocky-mountain-lake-tours'
      fullPath: '/ko/rocky-mountain-lake-tours'
      preLoaderRoute: typeof KoRockyMountainLakeToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/reviews': {
      id: '/ko/reviews'
      path: '/ko/reviews'
      fullPath: '/ko/reviews'
      preLoaderRoute: typeof KoReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/privacy': {
      id: '/ko/privacy'
      path: '/ko/privacy'
      fullPath: '/ko/privacy'
      preLoaderRoute: typeof KoPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/faq': {
      id: '/ko/faq'
      path: '/ko/faq'
      fullPath: '/ko/faq'
      preLoaderRoute: typeof KoFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/destinations': {
      id: '/ko/destinations'
      path: '/ko/destinations'
      fullPath: '/ko/destinations'
      preLoaderRoute: typeof KoDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/contact': {
      id: '/ko/contact'
      path: '/ko/contact'
      fullPath: '/ko/contact'
      preLoaderRoute: typeof KoContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/blog': {
      id: '/ko/blog'
      path: '/ko/blog'
      fullPath: '/ko/blog'
      preLoaderRoute: typeof KoBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/about': {
      id: '/ko/about'
      path: '/ko/about'
      fullPath: '/ko/about'
      preLoaderRoute: typeof KoAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/tours/': {
      id: '/zh/tours/'
      path: '/zh/tours'
      fullPath: '/zh/tours/'
      preLoaderRoute: typeof ZhToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/tours/': {
      id: '/ko/tours/'
      path: '/ko/tours'
      fullPath: '/ko/tours/'
      preLoaderRoute: typeof KoToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/tours/$slug': {
      id: '/zh/tours/$slug'
      path: '/zh/tours/$slug'
      fullPath: '/zh/tours/$slug'
      preLoaderRoute: typeof ZhToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/tours/$slug': {
      id: '/ko/tours/$slug'
      path: '/ko/tours/$slug'
      fullPath: '/ko/tours/$slug'
      preLoaderRoute: typeof KoToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToursRouteChildren {
  ToursSlugRoute: typeof ToursSlugRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursSlugRoute: ToursSlugRoute,
  ToursIndexRoute: ToursIndexRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  RockyMountainLakeToursRoute: RockyMountainLakeToursRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToursRoute: ToursRouteWithChildren,
  KoAboutRoute: KoAboutRoute,
  KoBlogRoute: KoBlogRoute,
  KoContactRoute: KoContactRoute,
  KoDestinationsRoute: KoDestinationsRoute,
  KoFaqRoute: KoFaqRoute,
  KoPrivacyRoute: KoPrivacyRoute,
  KoReviewsRoute: KoReviewsRoute,
  KoRockyMountainLakeToursRoute: KoRockyMountainLakeToursRoute,
  KoTermsRoute: KoTermsRoute,
  ZhAboutRoute: ZhAboutRoute,
  ZhBlogRoute: ZhBlogRoute,
  ZhContactRoute: ZhContactRoute,
  ZhDestinationsRoute: ZhDestinationsRoute,
  ZhFaqRoute: ZhFaqRoute,
  ZhGalleryRoute: ZhGalleryRoute,
  ZhPrivacyRoute: ZhPrivacyRoute,
  ZhReviewsRoute: ZhReviewsRoute,
  ZhRockyMountainLakeToursRoute: ZhRockyMountainLakeToursRoute,
  ZhTermsRoute: ZhTermsRoute,
  KoIndexRoute: KoIndexRoute,
  ZhIndexRoute: ZhIndexRoute,
  KoToursSlugRoute: KoToursSlugRoute,
  ZhToursSlugRoute: ZhToursSlugRoute,
  KoToursIndexRoute: KoToursIndexRoute,
  ZhToursIndexRoute: ZhToursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
