/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZhIndexRouteImport } from './routes/zh/index'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as KoIndexRouteImport } from './routes/ko/index'
import { Route as ZhTermsRouteImport } from './routes/zh/terms'
import { Route as ZhReviewsRouteImport } from './routes/zh/reviews'
import { Route as ZhPrivacyRouteImport } from './routes/zh/privacy'
import { Route as ZhFaqRouteImport } from './routes/zh/faq'
import { Route as ZhDestinationsRouteImport } from './routes/zh/destinations'
import { Route as ZhContactRouteImport } from './routes/zh/contact'
import { Route as ZhBlogRouteImport } from './routes/zh/blog'
import { Route as ZhAboutRouteImport } from './routes/zh/about'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'
import { Route as KoSplatRouteImport } from './routes/ko/$'
import { Route as ZhToursIndexRouteImport } from './routes/zh/tours.index'
import { Route as ZhToursSlugRouteImport } from './routes/zh/tours.$slug'

const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhIndexRoute = ZhIndexRouteImport.update({
  id: '/zh/',
  path: '/zh/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToursRoute,
} as any)
const KoIndexRoute = KoIndexRouteImport.update({
  id: '/ko/',
  path: '/ko/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhTermsRoute = ZhTermsRouteImport.update({
  id: '/zh/terms',
  path: '/zh/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhReviewsRoute = ZhReviewsRouteImport.update({
  id: '/zh/reviews',
  path: '/zh/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhPrivacyRoute = ZhPrivacyRouteImport.update({
  id: '/zh/privacy',
  path: '/zh/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhFaqRoute = ZhFaqRouteImport.update({
  id: '/zh/faq',
  path: '/zh/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhDestinationsRoute = ZhDestinationsRouteImport.update({
  id: '/zh/destinations',
  path: '/zh/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhContactRoute = ZhContactRouteImport.update({
  id: '/zh/contact',
  path: '/zh/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhBlogRoute = ZhBlogRouteImport.update({
  id: '/zh/blog',
  path: '/zh/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhAboutRoute = ZhAboutRouteImport.update({
  id: '/zh/about',
  path: '/zh/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToursRoute,
} as any)
const KoSplatRoute = KoSplatRouteImport.update({
  id: '/ko/$',
  path: '/ko/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhToursIndexRoute = ZhToursIndexRouteImport.update({
  id: '/zh/tours/',
  path: '/zh/tours/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZhToursSlugRoute = ZhToursSlugRouteImport.update({
  id: '/zh/tours/$slug',
  path: '/zh/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/tours': typeof ToursRouteWithChildren
  '/ko/$': typeof KoSplatRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/blog': typeof ZhBlogRoute
  '/zh/contact': typeof ZhContactRoute
  '/zh/destinations': typeof ZhDestinationsRoute
  '/zh/faq': typeof ZhFaqRoute
  '/zh/privacy': typeof ZhPrivacyRoute
  '/zh/reviews': typeof ZhReviewsRoute
  '/zh/terms': typeof ZhTermsRoute
  '/ko/': typeof KoIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/zh/tours/$slug': typeof ZhToursSlugRoute
  '/zh/tours/': typeof ZhToursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/ko/$': typeof KoSplatRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/blog': typeof ZhBlogRoute
  '/zh/contact': typeof ZhContactRoute
  '/zh/destinations': typeof ZhDestinationsRoute
  '/zh/faq': typeof ZhFaqRoute
  '/zh/privacy': typeof ZhPrivacyRoute
  '/zh/reviews': typeof ZhReviewsRoute
  '/zh/terms': typeof ZhTermsRoute
  '/ko': typeof KoIndexRoute
  '/tours': typeof ToursIndexRoute
  '/zh': typeof ZhIndexRoute
  '/zh/tours/$slug': typeof ZhToursSlugRoute
  '/zh/tours': typeof ZhToursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/tours': typeof ToursRouteWithChildren
  '/ko/$': typeof KoSplatRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/zh/about': typeof ZhAboutRoute
  '/zh/blog': typeof ZhBlogRoute
  '/zh/contact': typeof ZhContactRoute
  '/zh/destinations': typeof ZhDestinationsRoute
  '/zh/faq': typeof ZhFaqRoute
  '/zh/privacy': typeof ZhPrivacyRoute
  '/zh/reviews': typeof ZhReviewsRoute
  '/zh/terms': typeof ZhTermsRoute
  '/ko/': typeof KoIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/zh/': typeof ZhIndexRoute
  '/zh/tours/$slug': typeof ZhToursSlugRoute
  '/zh/tours/': typeof ZhToursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/tours'
    | '/ko/$'
    | '/tours/$slug'
    | '/zh/about'
    | '/zh/blog'
    | '/zh/contact'
    | '/zh/destinations'
    | '/zh/faq'
    | '/zh/privacy'
    | '/zh/reviews'
    | '/zh/terms'
    | '/ko/'
    | '/tours/'
    | '/zh/'
    | '/zh/tours/$slug'
    | '/zh/tours/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/ko/$'
    | '/tours/$slug'
    | '/zh/about'
    | '/zh/blog'
    | '/zh/contact'
    | '/zh/destinations'
    | '/zh/faq'
    | '/zh/privacy'
    | '/zh/reviews'
    | '/zh/terms'
    | '/ko'
    | '/tours'
    | '/zh'
    | '/zh/tours/$slug'
    | '/zh/tours'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/destinations'
    | '/faq'
    | '/privacy'
    | '/reviews'
    | '/terms'
    | '/tours'
    | '/ko/$'
    | '/tours/$slug'
    | '/zh/about'
    | '/zh/blog'
    | '/zh/contact'
    | '/zh/destinations'
    | '/zh/faq'
    | '/zh/privacy'
    | '/zh/reviews'
    | '/zh/terms'
    | '/ko/'
    | '/tours/'
    | '/zh/'
    | '/zh/tours/$slug'
    | '/zh/tours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  TermsRoute: typeof TermsRoute
  ToursRoute: typeof ToursRouteWithChildren
  KoSplatRoute: typeof KoSplatRoute
  ZhAboutRoute: typeof ZhAboutRoute
  ZhBlogRoute: typeof ZhBlogRoute
  ZhContactRoute: typeof ZhContactRoute
  ZhDestinationsRoute: typeof ZhDestinationsRoute
  ZhFaqRoute: typeof ZhFaqRoute
  ZhPrivacyRoute: typeof ZhPrivacyRoute
  ZhReviewsRoute: typeof ZhReviewsRoute
  ZhTermsRoute: typeof ZhTermsRoute
  KoIndexRoute: typeof KoIndexRoute
  ZhIndexRoute: typeof ZhIndexRoute
  ZhToursSlugRoute: typeof ZhToursSlugRoute
  ZhToursIndexRoute: typeof ZhToursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/': {
      id: '/zh/'
      path: '/zh'
      fullPath: '/zh/'
      preLoaderRoute: typeof ZhIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/': {
      id: '/tours/'
      path: '/'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof ToursRoute
    }
    '/ko/': {
      id: '/ko/'
      path: '/ko'
      fullPath: '/ko/'
      preLoaderRoute: typeof KoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/terms': {
      id: '/zh/terms'
      path: '/zh/terms'
      fullPath: '/zh/terms'
      preLoaderRoute: typeof ZhTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/reviews': {
      id: '/zh/reviews'
      path: '/zh/reviews'
      fullPath: '/zh/reviews'
      preLoaderRoute: typeof ZhReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/privacy': {
      id: '/zh/privacy'
      path: '/zh/privacy'
      fullPath: '/zh/privacy'
      preLoaderRoute: typeof ZhPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/faq': {
      id: '/zh/faq'
      path: '/zh/faq'
      fullPath: '/zh/faq'
      preLoaderRoute: typeof ZhFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/destinations': {
      id: '/zh/destinations'
      path: '/zh/destinations'
      fullPath: '/zh/destinations'
      preLoaderRoute: typeof ZhDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/contact': {
      id: '/zh/contact'
      path: '/zh/contact'
      fullPath: '/zh/contact'
      preLoaderRoute: typeof ZhContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/blog': {
      id: '/zh/blog'
      path: '/zh/blog'
      fullPath: '/zh/blog'
      preLoaderRoute: typeof ZhBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/about': {
      id: '/zh/about'
      path: '/zh/about'
      fullPath: '/zh/about'
      preLoaderRoute: typeof ZhAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof ToursRoute
    }
    '/ko/$': {
      id: '/ko/$'
      path: '/ko/$'
      fullPath: '/ko/$'
      preLoaderRoute: typeof KoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/tours/': {
      id: '/zh/tours/'
      path: '/zh/tours'
      fullPath: '/zh/tours/'
      preLoaderRoute: typeof ZhToursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zh/tours/$slug': {
      id: '/zh/tours/$slug'
      path: '/zh/tours/$slug'
      fullPath: '/zh/tours/$slug'
      preLoaderRoute: typeof ZhToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToursRouteChildren {
  ToursSlugRoute: typeof ToursSlugRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursSlugRoute: ToursSlugRoute,
  ToursIndexRoute: ToursIndexRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  TermsRoute: TermsRoute,
  ToursRoute: ToursRouteWithChildren,
  KoSplatRoute: KoSplatRoute,
  ZhAboutRoute: ZhAboutRoute,
  ZhBlogRoute: ZhBlogRoute,
  ZhContactRoute: ZhContactRoute,
  ZhDestinationsRoute: ZhDestinationsRoute,
  ZhFaqRoute: ZhFaqRoute,
  ZhPrivacyRoute: ZhPrivacyRoute,
  ZhReviewsRoute: ZhReviewsRoute,
  ZhTermsRoute: ZhTermsRoute,
  KoIndexRoute: KoIndexRoute,
  ZhIndexRoute: ZhIndexRoute,
  ZhToursSlugRoute: ZhToursSlugRoute,
  ZhToursIndexRoute: ZhToursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
